swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/account:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Account API
      description: API for getting user accounts
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: User accounts retrieved successully
          schema:
            $ref: '#/definitions/AccountResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/account/{accountid}/transactions/{month}:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Transactions API
      description: API for getting transactions for the month number or current month
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: month
          description: month to get
          required: true
          type: integer
        - in: path
          name: accountid
          description: account id
          required: true
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: User transactions retrieved successully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/transactions/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Transaction details API
      description: API for getting the detail of the transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: id
          description: Transaction ID
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: User transaction detail retrieved successully
          schema:
            $ref: '#/definitions/TransactionDetail'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/transaction/{id}:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Transaction detail API
      description: API for create the category of the transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: id
          description: Transaction ID
          required: true
          type: string
        - in: body
          name: body
          description: Transaction category
          required: true
          schema:
            properties:
              category:
                type: string
              notes:
                type: string
      produces:
        - application/json
      responses:
        '201':
          description: User transactions category created successully
          schema:
             properties:
              category:
                type: string
              notes:
                type: string
        '422':
          description: Unprocessable Entity 
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Transaction detail API
      description: API for update the category of the transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: id
          description: Transaction ID
          required: true
          type: string
        - in: body
          name: body
          description: Transaction category
          required: true
          schema:
            properties:
              category:
                type: string
              notes:
                type: string
      produces:
        - application/json
      responses:
        '200':
          description: User transactions category updated successully
          schema:
             properties:
              category:
                type: string
        '422':
          description: Unprocessable Entity 
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Transaction detail API
      description: API for delete the category of the transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: id
          description: Transaction ID
          required: true
          type: string
      responses:
        '204':
          description: Transactions category deleted successully
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  AccountResponse:
    type: array
    items:
      $ref: '#/definitions/Account'
  TransactionResponse:
    type: array
    items:
      $ref: '#/definitions/Transaction'
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  Account:
    type: object
    properties:
      id:
        type: string
      type:
        type: string
      balance:
        type: number
  Transaction:
    type: object
    properties:
      id:
        type: string
      date:
        type: integer
      description:
        type: string
      amount:
        type: number
      balance:
        type: number
  TransactionDetail:
    type: object
    properties:
      id:
        type: string
      type:
        type: string
      category:
        type: string
      notes:
        type: string
        